/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aim.duty.duty_build.ui;

import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;

import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListDataEvent;
import javax.swing.table.DefaultTableModel;

import com.aim.duty.duty_build.cache.config.MagicConfigCache;
import com.aim.duty.duty_build.cache.config.OreConfigCache;
import com.aim.duty.duty_build.cache.config.PlayCountConfigCache;
import com.aim.duty.duty_build.ui.data.RoleData;
import com.aim.duty.duty_build_entity.navigation.BuildProtocalId;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.CS_ChooseMaterial;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.CS_CreateRole;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.CS_GetResult;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.CS_GetResult.Brick.Magic;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.CS_GetWallValue;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.CS_ReplaceBrick;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.SC_GetResult;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.SC_GetResult.Brick;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.SC_GetWallValue;
import com.aim.duty.duty_build_entity.protobuf.protocal.Build.SC_ReplaceBrick;
import com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_BuyProp;
import com.aim.duty.duty_build_entity.protobuf.protocal.Trade.CS_SaleProp;
import com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_BuyProp;
import com.aim.duty.duty_build_entity.protobuf.protocal.Trade.SC_SaleProp;
import com.aim.game_base.entity.net.base.Protocal.PT;
import com.aim.game_base.net.SpringContext;
import com.aim.game_base.net.Utils;
import com.aim.game_base.net.WanClient;

/**
 *
 * @author asus
 */
public class MainFrame extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
    	initLayout();
        initComponents();
        initCode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("create architect");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setColumns(11);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField2.setColumns(11);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("选择材料");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("选择数量");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("仓库");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("选择材料");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setColumnSelectionAllowed(false);
        jTable1.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jButton4.setText("替换砖块");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");
        
        jButton5.setText("出售");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("购买");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	EventQueue.invokeLater(new Runnable(){

			@Override
			public void run() {
				// TODO Auto-generated method stub
				String account = jTextField1.getText();
				String name = jTextField2.getText();
				Object obj = jComboBox1.getModel().getElementAt(0);
				if (obj == null) {
					// BuildService buildService =
					// SpringContext.getBean("buildService");
					// buildService.createRole(account, name);
					PT cs = PT.newBuilder().setProtocal(BuildProtocalId.CREATE_ROLE).setData(
							CS_CreateRole.newBuilder().setAccount(account).setName(name).build().toByteString()).build();
					WanClient buildClient = SpringContext.getBean("buildServer");
					buildClient.send(cs);
				}

			}
    		
    	});
    }      

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		CS_GetResult.Builder csGetResultBuilder = CS_GetResult.newBuilder();
		int count = Utils.getRandomNum(RoleData.num);
		for (int i = 0; i < 5; i++) {
			CS_GetResult.Brick.Builder csBrickBuilder = CS_GetResult.Brick.newBuilder();
			Map<Integer, CS_GetResult.Brick.Magic> csMagics = new HashMap<>();

			int magicCount = Utils.getRandomNum(1,4);
			for (int j = 0; j < magicCount; j++) {
				Magic magic = CS_GetResult.Brick.Magic.newBuilder()
						.setDuration(Utils.getRandomNum(20)).setMagicId(Utils.getRandomNum(3))
						.setValue(Utils.getRandomNum(20)).build();
				csMagics.put(magic.getMagicId(), magic);
			}
			csBrickBuilder.putAllMagics(csMagics);
			
			CS_GetResult.Brick csBrick = csBrickBuilder.build();
			
			csGetResultBuilder.addBricks(csBrick);
		}
		WanClient buildClient = SpringContext.getBean("buildServer");
		buildClient.send(PT.newBuilder().setProtocal(BuildProtocalId.GET_RESULT).setData(csGetResultBuilder.build().toByteString()).build());
		
		
	}
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		int configId = OreConfigCache.getConfigIdByIndex(jComboBox2.getSelectedIndex());
		int playCount = PlayCountConfigCache.getCounts().get(jComboBox3.getSelectedIndex());
		PT cs = PT.newBuilder().setProtocal(BuildProtocalId.CHOOSE_MATERIAL).setData(CS_ChooseMaterial.newBuilder()
				.setBrickSourceId(configId).setBrickSourceNum(playCount).build().toByteString()).build();
		WanClient buildClient = SpringContext.getBean("buildServer");
		buildClient.send(cs);
	}

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }       
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				// TODO Auto-generated method stub
				com.aim.duty.duty_build_entity.bo.Brick b = (com.aim.duty.duty_build_entity.bo.Brick) jComboBox4
						.getSelectedItem();
				int propId = b != null ? b.getId() : -1;
				int row = jTable1.getSelectedRow();
				int column = jTable1.getSelectedColumn();
				int indexAtWall = row * 4 + column;
				indexAtWall = indexAtWall < 0 ? -1 : indexAtWall;

				WanClient buildServer = SpringContext.getBean("buildServer");
				buildServer.send(PT
						.newBuilder()
						.setProtocal(BuildProtocalId.REPLACE_BRICK)
						.setData(
								CS_ReplaceBrick.newBuilder().setPropId(propId).setIndexAtWall(indexAtWall).build()
										.toByteString()).build());
			}

		});
    	
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	com.aim.duty.duty_build_entity.bo.Brick b = (com.aim.duty.duty_build_entity.bo.Brick) jComboBox4
				.getSelectedItem();
    	String str = jTextField3.getText();
    	String[] data = str.split(" ");
    	int num = Integer.parseInt(data[0]);
    	int price = Integer.parseInt(data[1]);
    	
		WanClient buildServer = SpringContext.getBean("buildServer");
		buildServer.send(PT
				.newBuilder()
				.setProtocal(BuildProtocalId.TRADE_SALE_PROP)
				.setData(
						CS_SaleProp.newBuilder().setPropId(b.getId()).setNum(num).setSinglePrice(price).build()
								.toByteString()).build());

    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		String str = jTextField3.getText();
		String[] data = str.split(" ");
		int commodityId = Integer.parseInt(data[0]);
		int num = Integer.parseInt(data[1]);

		WanClient buildServer = SpringContext.getBean("buildServer");
		buildServer.send(PT.newBuilder().setProtocal(BuildProtocalId.TRADE_BUY_PROP)
				.setData(CS_BuyProp.newBuilder().setNum(num).setCommodityId(commodityId).build().toByteString())
				.build());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration
    
    public javax.swing.JComboBox getjComboBox1() {
		return jComboBox1;
	}    
    
	public void initCode() {
		// TODO Auto-generated method stub
		EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				// TODO Auto-generated method stub				
				DefaultComboBoxModel roleModel = (DefaultComboBoxModel) jComboBox1.getModel();
				roleModel.removeAllElements();
				roleModel.addListDataListener(new ListDataListenerAdapter() {

					@Override
					public void contentsChanged(ListDataEvent e) {
						// TODO Auto-generated method stub
						DefaultComboBoxModel model = (DefaultComboBoxModel) e.getSource();
						int index = model.getIndexOf(model.getSelectedItem());
					}

				});
				jTextField1.setText("1");
				jTextField2.setText("1");
				jTextField1.setEditable(false);
				jTextField2.setEditable(false);

				DefaultComboBoxModel materialModel = (DefaultComboBoxModel) jComboBox2.getModel();
				materialModel.removeAllElements();
				for (String name : OreConfigCache.getNames())
					materialModel.addElement(name);

				materialModel.addListDataListener(new ListDataListenerAdapter() {

					@Override
					public void contentsChanged(ListDataEvent e) {
						// TODO Auto-generated method stub

					}
				});

				DefaultComboBoxModel countModel = (DefaultComboBoxModel) jComboBox3.getModel();
				countModel.removeAllElements();
				for (Integer count : PlayCountConfigCache.getCounts())
					countModel.addElement(count);

				countModel.addListDataListener(new ListDataListenerAdapter() {

					@Override
					public void contentsChanged(ListDataEvent e) {
						// TODO Auto-generated method stub
						
					}
				});

				DefaultComboBoxModel storeModel = (DefaultComboBoxModel) jComboBox4.getModel();
				storeModel.removeAllElements();
				
				storeModel.addListDataListener(new ListDataListenerAdapter(){
					@Override
					public void contentsChanged(ListDataEvent e) {
						// TODO Auto-generated method stub
//						super.contentsChanged(e);
						DefaultComboBoxModel tableModel = (DefaultComboBoxModel)e.getSource();
						final com.aim.duty.duty_build_entity.bo.Brick b = (com.aim.duty.duty_build_entity.bo.Brick) tableModel.getSelectedItem();
						EventQueue.invokeLater(new Runnable(){

							@Override
							public void run() {
								// TODO Auto-generated method stub
								
								if (b == null) {
									jTextArea1.setText("");
									return;
								}
								StringBuilder sb = new StringBuilder();
								sb.append("名称：").append(b).append("\n\n");
								
								for(com.aim.duty.duty_build_entity.po.Magic magic :b.getMagicMap().values()){
									sb.append("魔法:").append(MagicConfigCache.getMagicConfigById(magic.getMagicId()).getName()).append("\n");
									sb.append("持续时间:").append(magic.getDuration()).append("\n");
									sb.append("力量:").append(magic.getValue()).append("\n\n");
								}
								jTextArea1.setText(sb.toString());
							}
							
						});
					}
				});
				
				jTextField3.setText("1 14");
			
			}

		});

	}

    private void initLayout() {
		// TODO Auto-generated method stub
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
	}
    
    public void start(final MainFrame frame) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				frame.setVisible(true);
			}
		});
	}

	@Override
	public void update(Observable o, Object arg) {
		// TODO Auto-generated method stub
		List data = (List) arg;
		String message = (String) data.get(0);
		if (message.equals("addRole")) {
			this.addRole();
		}else if(message.equals("chooseMaterial")){
			this.chooseMaterial();
		}else if(message.equals("getResult")){
			SC_GetResult result = (SC_GetResult)data.get(1);
			this.getResult(result);
		}else if(message.equals("addBrickIntoWall")){
			SC_ReplaceBrick result= (SC_ReplaceBrick)data.get(1);
			this.replaceBrick(result);
		}else if(message.equals("getWallValue")){
			SC_GetWallValue result = (SC_GetWallValue) data.get(1);
			this.getWallValue(result);
		}else if(message.equals("saleProp")){
			SC_SaleProp result= (SC_SaleProp)data.get(1);
			this.saleProp(result);
		}else if(message.equals("buyProp")){
			SC_BuyProp result = (SC_BuyProp)data.get(1);
			this.buyProp(result);
		}
	}

	private void buyProp(final SC_BuyProp result) {
		// TODO Auto-generated method stub
		
		EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				// TODO Auto-generated method stub
				com.aim.duty.duty_build_entity.bo.Brick brick = new com.aim.duty.duty_build_entity.bo.Brick(){
					public String toString() {
						// TODO Auto-generated method stub
						StringBuilder sb= new StringBuilder();
						for(com.aim.duty.duty_build_entity.po.Magic magic:this.getMagicMap().values()){
							sb.append(MagicConfigCache.getMagicConfigById(magic.getMagicId()).getName());								
						}
						sb.append(OreConfigCache.getAllMap().get(this.getMineId()).getName());
						return sb.toString();
					}
				};
				brick.deserialize(result.getAbstractProp());
				brick.setId(result.getPropId());
				DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox4.getModel();
				model.addElement(brick);
			}
		});
	}

	private void saleProp(SC_SaleProp result) {
		// TODO Auto-generated method stub
		EventQueue.invokeLater(new Runnable(){

			@Override
			public void run() {
				// TODO Auto-generated method stub
				DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox4.getModel();
				int index = jComboBox4.getSelectedIndex();
				model.removeElementAt(index);
			}
			
		});
	}

	private void getWallValue(final SC_GetWallValue result) {
		// TODO Auto-generated method stub
		EventQueue.invokeLater(new Runnable() {
			
			@Override
			public void run() {
				// TODO Auto-generated method stub
				StringBuilder sb= new StringBuilder();
				sb.append("血量").append(result.getBlood());
				for(SC_GetWallValue.Magic magic:result.getMagicsMap().values()){
					String magicName = MagicConfigCache.getMagicConfigById(magic.getMagicId()).getName();
					sb.append(magicName).append("伤害:").append(magic.getValue()).append("持续时间").append(magic.getDuration());
				}
				jLabel4.setText(sb.toString());
			}
		});
		
	}

	private void replaceBrick(SC_ReplaceBrick result) {
		// TODO Auto-generated method stub
		EventQueue.invokeLater(new Runnable(){

			@Override
			public void run() {
				// TODO Auto-generated method stub

				DefaultComboBoxModel comboModel = (DefaultComboBoxModel) jComboBox4.getModel();
				DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

				com.aim.duty.duty_build_entity.bo.Brick propBrick = (com.aim.duty.duty_build_entity.bo.Brick) jComboBox4.getSelectedItem();
				int row = jTable1.getSelectedRow();
				int column = jTable1.getSelectedColumn();
				int indexAtWall = row * 4 + column;
				indexAtWall = indexAtWall < 0 ? -1 : indexAtWall;

				if (row == -1 && column == -1) {
					return;
				}

				com.aim.duty.duty_build_entity.bo.Brick brickAtWall = (com.aim.duty.duty_build_entity.bo.Brick) tableModel
						.getValueAt(row, column);

				if (propBrick == null && brickAtWall == null) {
					return;
				} else if (propBrick != null && brickAtWall != null) {
					comboModel.removeElementAt(jComboBox4.getSelectedIndex());
					tableModel.setValueAt(null, row, column);

					comboModel.insertElementAt(brickAtWall,0);
					tableModel.setValueAt(propBrick, row, column);
				}else if(propBrick!=null){
					tableModel.setValueAt(propBrick, row, column);
					comboModel.removeElementAt(jComboBox4.getSelectedIndex());
				} else if (brickAtWall != null) {
					comboModel.insertElementAt(brickAtWall, 0);
					tableModel.setValueAt(null, row, column);
				}
				
				WanClient buildServer = SpringContext.getBean("buildServer");
				buildServer.send(PT.newBuilder().setProtocal(BuildProtocalId.GET_WALL_VALUE).setData(CS_GetWallValue.newBuilder().build().toByteString()).build());
				

			}
			
		});
	}

	private void getResult(final SC_GetResult result) {
		// TODO Auto-generated method stub
		EventQueue.invokeLater(new Runnable(){

			@Override
			public void run() {
				// TODO Auto-generated method stub				
				DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox4.getModel();
				for (Brick brick : result.getBricksList()) {
					com.aim.duty.duty_build_entity.bo.Brick b = new com.aim.duty.duty_build_entity.bo.Brick(){
						@Override
						public String toString() {
							// TODO Auto-generated method stub
							StringBuilder sb= new StringBuilder();
							for(com.aim.duty.duty_build_entity.po.Magic magic:this.getMagicMap().values()){
								sb.append(MagicConfigCache.getMagicConfigById(magic.getMagicId()).getName());								
							}
							sb.append(OreConfigCache.getAllMap().get(this.getMineId()).getName());
							return sb.toString();
						}
					};
					b.setMineId(brick.getMineId());
					b.setId(brick.getId());

					for (SC_GetResult.Brick.Magic magic : brick.getMagicsMap().values()) {
						com.aim.duty.duty_build_entity.po.Magic m = new com.aim.duty.duty_build_entity.po.Magic();
						m.setDuration(magic.getDuration());
						m.setValue(magic.getValue());
						m.setMagicId(magic.getMagicId());
						
						b.getMagicMap().put(magic.getMagicId(), m);
					}
					
					model.addElement(b);

				}
				jButton3.setEnabled(true);
			}
			
		});
	}

	private void chooseMaterial() {
		// TODO Auto-generated method stub
		EventQueue.invokeLater(new Runnable(){
			@Override
			public void run() {
				// TODO Auto-generated method stub
				jButton3.setEnabled(false);
				RoleData.sourceId = OreConfigCache.getConfigIdByIndex(jComboBox2.getSelectedIndex());
				RoleData.num = PlayCountConfigCache.getCounts().get(jComboBox3.getSelectedIndex());
			}
		});
	}

	private void addRole() {
		EventQueue.invokeLater(new Runnable() {

			@Override
			public void run() {
				// TODO Auto-generated method stub
				
				DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox1.getModel();
				String name =jTextField2.getText();
				model.addElement(name);
			}
		});
	}
	
	private List<List> roleNameList = new ArrayList<>();
}
