// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Build.proto

package com.aim.duty.duty_build.entity.protobuf.protocal;

public final class Build {
  private Build() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CS_CreateArchitectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aim.duty.duty_build.entity.protobuf.protocal.CS_CreateArchitect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string account = 1;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>optional string account = 1;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.aim.duty.duty_build.entity.protobuf.protocal.CS_CreateArchitect}
   */
  public  static final class CS_CreateArchitect extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aim.duty.duty_build.entity.protobuf.protocal.CS_CreateArchitect)
      CS_CreateArchitectOrBuilder {
    // Use CS_CreateArchitect.newBuilder() to construct.
    private CS_CreateArchitect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CS_CreateArchitect() {
      account_ = "";
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CS_CreateArchitect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect.class, com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private volatile java.lang.Object account_;
    /**
     * <code>optional string account = 1;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>optional string account = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, account_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, account_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect)) {
        return super.equals(obj);
      }
      com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect other = (com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect) obj;

      boolean result = true;
      result = result && getAccount()
          .equals(other.getAccount());
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aim.duty.duty_build.entity.protobuf.protocal.CS_CreateArchitect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aim.duty.duty_build.entity.protobuf.protocal.CS_CreateArchitect)
        com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect.class, com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect.Builder.class);
      }

      // Construct using com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        account_ = "";

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_descriptor;
      }

      public com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect getDefaultInstanceForType() {
        return com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect.getDefaultInstance();
      }

      public com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect build() {
        com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect buildPartial() {
        com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect result = new com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect(this);
        result.account_ = account_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect) {
          return mergeFrom((com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect other) {
        if (other == com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect.getDefaultInstance()) return this;
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>optional string account = 1;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string account = 1;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aim.duty.duty_build.entity.protobuf.protocal.CS_CreateArchitect)
    }

    // @@protoc_insertion_point(class_scope:com.aim.duty.duty_build.entity.protobuf.protocal.CS_CreateArchitect)
    private static final com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect();
    }

    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CS_CreateArchitect>
        PARSER = new com.google.protobuf.AbstractParser<CS_CreateArchitect>() {
      public CS_CreateArchitect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CS_CreateArchitect(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CS_CreateArchitect> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CS_CreateArchitect> getParserForType() {
      return PARSER;
    }

    public com.aim.duty.duty_build.entity.protobuf.protocal.Build.CS_CreateArchitect getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SC_CreateArchitectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aim.duty.duty_build.entity.protobuf.protocal.SC_CreateArchitect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 success = 1;</code>
     */
    int getSuccess();
  }
  /**
   * Protobuf type {@code com.aim.duty.duty_build.entity.protobuf.protocal.SC_CreateArchitect}
   */
  public  static final class SC_CreateArchitect extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aim.duty.duty_build.entity.protobuf.protocal.SC_CreateArchitect)
      SC_CreateArchitectOrBuilder {
    // Use SC_CreateArchitect.newBuilder() to construct.
    private SC_CreateArchitect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SC_CreateArchitect() {
      success_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SC_CreateArchitect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              success_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect.class, com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private int success_;
    /**
     * <code>optional int32 success = 1;</code>
     */
    public int getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != 0) {
        output.writeInt32(1, success_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, success_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect)) {
        return super.equals(obj);
      }
      com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect other = (com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + getSuccess();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aim.duty.duty_build.entity.protobuf.protocal.SC_CreateArchitect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aim.duty.duty_build.entity.protobuf.protocal.SC_CreateArchitect)
        com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect.class, com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect.Builder.class);
      }

      // Construct using com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        success_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aim.duty.duty_build.entity.protobuf.protocal.Build.internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_descriptor;
      }

      public com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect getDefaultInstanceForType() {
        return com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect.getDefaultInstance();
      }

      public com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect build() {
        com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect buildPartial() {
        com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect result = new com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect) {
          return mergeFrom((com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect other) {
        if (other == com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect.getDefaultInstance()) return this;
        if (other.getSuccess() != 0) {
          setSuccess(other.getSuccess());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int success_ ;
      /**
       * <code>optional int32 success = 1;</code>
       */
      public int getSuccess() {
        return success_;
      }
      /**
       * <code>optional int32 success = 1;</code>
       */
      public Builder setSuccess(int value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.aim.duty.duty_build.entity.protobuf.protocal.SC_CreateArchitect)
    }

    // @@protoc_insertion_point(class_scope:com.aim.duty.duty_build.entity.protobuf.protocal.SC_CreateArchitect)
    private static final com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect();
    }

    public static com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SC_CreateArchitect>
        PARSER = new com.google.protobuf.AbstractParser<SC_CreateArchitect>() {
      public SC_CreateArchitect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SC_CreateArchitect(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SC_CreateArchitect> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SC_CreateArchitect> getParserForType() {
      return PARSER;
    }

    public com.aim.duty.duty_build.entity.protobuf.protocal.Build.SC_CreateArchitect getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Build.proto\0220com.aim.duty.duty_build.e" +
      "ntity.protobuf.protocal\"3\n\022CS_CreateArch" +
      "itect\022\017\n\007account\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"%\n\022" +
      "SC_CreateArchitect\022\017\n\007success\030\001 \001(\005b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_CS_CreateArchitect_descriptor,
        new java.lang.String[] { "Account", "Name", });
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aim_duty_duty_build_entity_protobuf_protocal_SC_CreateArchitect_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
